name: "Format Check"

permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write

on:
  push:
    branches:
      - 'main'
    tags: '*'
  pull_request:

jobs:
  format-check:
    name: "Format Check"
    uses: "ITensor/ITensorActions/.github/workflows/FormatCheck.yml@main"
