name: "Format Check"

on:
  pull_request:

permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write

jobs:
  format-check:
    name: "Format Check"
    uses: "ITensor/ITensorActions/.github/workflows/FormatCheck.yml@main"
