name: "IntegrationTest"

on:
  push:
    branches:
      - 'main'
    tags: '*'
    paths:
      - 'Project.toml'
  pull_request:
    paths:
      - 'Project.toml'

jobs:
  integration-test:
    name: "IntegrationTest"
    strategy:
       matrix:
         repo:
           - '(ghuser = "ITensor", repo = "BlockSparseArrays")'
           - '(ghuser = "ITensor", repo = "DerivableInterfaces")'
           - '(ghuser = "ITensor", repo = "NamedDimsArrays")'
           - '(ghuser = "ITensor", repo = "TensorAlgebra")'
           - '(ghuser = "ITensor", repo = "UnallocatedArrays")'
    uses: "ITensor/ITensorActions/.github/workflows/IntegrationTest.yml@main"
    with:
      localregistry: "https://github.com/ITensor/ITensorRegistry.git"
      repo: "${{ matrix.repo }}"
